export type { JsonArray, JsonObject, JsonPrimitive, JsonValue } from './json.ts';
export {
  clamp,
  createSeededRandom,
  hashJson,
  hashString,
  lerp,
  normalize,
  randomRange,
  stableStringify,
  type SeededRandom,
} from './deterministic.ts';
export {
  STREAM_STATE_SCHEMA_VERSION,
  type BooleanStreamSample,
  type CategoricalStreamSample,
  type NormalizedStreamState,
  type NumericStreamSample,
  type StreamAdapter,
  type StreamAdapterResult,
  type StreamReadRequest,
  type StreamSample,
  type StreamSampleBase,
  type StreamSampleQuality,
  type StreamSource,
  type StreamStateSchemaVersion,
  type StreamStatus,
  type VectorStreamSample,
} from './stream.ts';
export {
  SCORE_INPUT_SCHEMA_VERSION,
  SCORE_OUTPUT_SCHEMA_VERSION,
  SCORE_VERSION_SCHEMA_VERSION,
  type AudioOutputState,
  type BoundedParameter,
  type HapticOutputState,
  type NamedParameter,
  type Score,
  type ScoreFrameContext,
  type ScoreInput,
  type ScoreInputSchemaVersion,
  type ScoreOutput,
  type ScoreOutputSchemaVersion,
  type ScoreTraceEntry,
  type ScoreVersionMetadata,
  type ScoreVersionSchemaVersion,
  type VisualOutputState,
} from './score.ts';
export {
  STREAM_SOURCE_REGISTRY_SCHEMA_VERSION,
  StreamSourceRegistry,
  createStreamSourceRegistry,
  isStreamSourceCompatibleWithScore,
  streamSourceModes,
  supportsStreamSourceMode,
  type ScoreCompatibilityCandidate,
  type StreamSourceAdapterMetadata,
  type StreamSourceCapability,
  type StreamSourceDefinition,
  type StreamSourceFixtureReference,
  type StreamSourceMode,
  type StreamSourceNormalizedMapping,
  type StreamSourceRegistrySchemaVersion,
  type StreamSourceSampleDefinition,
  type StreamSourceScoreCompatibility,
} from './stream-source-registry.ts';
export {
  REPLAY_SNAPSHOT_SCHEMA_VERSION,
  ReplaySnapshotValidationError,
  isReplaySnapshot,
  parseReplaySnapshot,
  validateReplaySnapshot,
  type ReplayFrame,
  type ReplaySnapshot,
  type ReplaySnapshotSchemaVersion,
} from './replay.ts';
