export {
  WEATHER_ADAPTER_ID,
  WEATHER_ADAPTER_VERSION,
  WEATHER_CREDENTIAL_ENV,
  WeatherAdapter,
  normalizeWeatherPayload,
  type NormalizeWeatherOptions,
  type RecordedWeatherPayload,
  type WeatherAdapterConfig,
  type WeatherAdapterFailurePayload,
  type WeatherAdapterRaw,
  type WeatherCurrentPayload,
  type WeatherFetch,
  type WeatherFetchResponse,
  type WeatherFixtureAdapterConfig,
  type WeatherLiveAdapterConfig,
  type WeatherLocation,
} from './weather.ts';
export {
  BROWSER_SENSOR_ADAPTER_ID,
  BROWSER_SENSOR_ADAPTER_VERSION,
  BrowserSensorAdapter,
  createBrowserSensorFixturePayload,
  normalizeBrowserSensorPayload,
  type BrowserMotionReading,
  type BrowserOrientationReading,
  type BrowserPointerReading,
  type BrowserSensorAdapterConfig,
  type BrowserSensorCapabilityState,
  type BrowserSensorFallbackState,
  type BrowserSensorFixtureAdapterConfig,
  type BrowserSensorLiveAdapterConfig,
  type BrowserSensorPermissionState,
  type BrowserSensorRead,
  type BrowserSensorReadingPayload,
  type BrowserSensorSession,
  type NormalizeBrowserSensorOptions,
  type RecordedBrowserSensorPayload,
} from './browser-sensor.ts';
export {
  MOCK_SENSOR_ADAPTER_ID,
  MOCK_SENSOR_ADAPTER_VERSION,
  MockSensorAdapter,
  normalizeMockSensorPayload,
  type MockSensorAdapterConfig,
  type MockSensorDevice,
  type MockSensorFixtureAdapterConfig,
  type MockSensorReadingPayload,
  type NormalizeMockSensorOptions,
  type RecordedMockSensorPayload,
} from './mock-sensor.ts';
export {
  BROWSER_SENSOR_STREAM_SOURCE_ID,
  browserSensorStreamSourceDefinition,
  WEATHER_STREAM_SOURCE_ID,
  createRegisteredStreamAdapter,
  streamSourceRegistry,
  weatherStreamSourceDefinition,
  type RegisteredStreamAdapter,
  type RegisteredStreamAdapterConfig,
} from './stream-source-registry.ts';
export { recordedOpenMeteoLondonCurrentV1 } from './fixtures/open-meteo-london-current-v1.ts';
