export {
  RECORDED_WEATHER_SCHEMA_VERSION,
  WEATHER_ADAPTER_ID,
  WEATHER_ADAPTER_VERSION,
  WeatherAdapter,
  normalizeWeatherObservation,
  type RecordedWeatherCurrentConditions,
  type RecordedWeatherPayload,
  type RecordedWeatherSchemaVersion,
  type RecordedWeatherWindVector,
  type WeatherAdapterConfig,
  type WeatherAdapterFailurePayload,
  type WeatherAdapterMode,
  type WeatherFailureCode,
  type WeatherFixtureAdapterConfig,
  type WeatherLiveAdapterConfig,
  type WeatherLocationDescriptor,
  type WeatherNormalizationOptions,
  type WeatherProviderCredentials,
  type WeatherProviderDescriptor,
  type WeatherRawPayload,
} from './weather/index.ts';
